# Generated by Django 4.1.6 on 2023-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
