# Generated by Django 4.1.6 on 2023-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
