# Generated by Django 4.1.6 on 2023-04-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.BooleanField(default=False),
        ),
    ]
