# Generated by Django 4.1.6 on 2023-04-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='fulanito', max_length=60),
            preserve_default=False,
        ),
    ]
